# Generated by Django 6.0.1 on 2026-03-27 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail_id', models.EmailField(max_length=254)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sold', models.IntegerField()),
                ('reviews', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Property_rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms', models.IntegerField(default=1)),
                ('bathroom', models.IntegerField(default=1)),
                ('kitchen', models.IntegerField(default=1)),
                ('store_room', models.IntegerField(default=1)),
                ('balcony', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Property_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('property_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('cost_of_living', models.IntegerField()),
                ('image', models.ImageField(upload_to='property_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.agent')),
            ],
        ),
    ]
