# Generated by Django 6.0.1 on 2026-03-27 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_image',
            field=models.ImageField(null=True, upload_to='agent_images/'),
        ),
        migrations.AddField(
            model_name='property_details',
            name='property_rooms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate.property_rooms'),
        ),
    ]
