# Generated by Django 6.0.1 on 2026-03-29 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_adminuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminUser',
            new_name='CreateAdminUser',
        ),
    ]
